# The Wonderful World of Python

In [6]:
a = 4
b = 2
c = 'hello'
print(type(a), type(b), type(c))
print('a + b = ', a + b)
c

<class 'int'> <class 'int'> <class 'str'>
a + b =  6


'hello'

## List

In [7]:
a = [1, 2, 3, 'hey', [10, 'never', 90], -32]
print(a)
print(len(a))

[1, 2, 3, 'hey', [10, 'never', 90], -32]
6


In [8]:
for i in range(len(a)):
    print(i, "-->", a[i])

0 --> 1
1 --> 2
2 --> 3
3 --> hey
4 --> [10, 'never', 90]
5 --> -32


In [10]:
for i in a:
    print(i)

1
2
3
hey
[10, 'never', 90]
-32


## Indexing

## Numpy
NumPy’s main object is the homogeneous multidimensional array.
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [18]:
import numpy as np

a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

print("a shape", a.shape)
print("a dims", a.ndim)
print("a rows", a.shape[0])
print("a cols", a.shape[1])
print("a type", a.dtype)

v = np.array([2,3,4,3,6,1,3,56,7,3,12])
print("v shape", v.shape)
print("v elems", v.shape[0])

a shape (3, 5)
a dims 2
a rows 3
a cols 5
a type int64
v shape (11,)
v elems 11


## Initial placeholders

In [35]:
print(np.zeros((3, 4)))
print(np.ones((3, 4)))
print(np.arange(10, 25, 5))
print(np.linspace(0, 2, 9))
print(np.full((2, 2), 7))
print(np.eye(3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b**2)
print(10 * np.sin(b))
print(a < 35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[0.         8.41470985 9.09297427 1.41120008]
[ True  True False False]


Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator (in python >=3.5) or the dot function or method:

In [26]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print('elementwise product\n', A * B)
print('matrix product\n', A @ B)
print('another product\n', A.dot(B))

elementwise product
 [[2 0]
 [0 4]]
matrix product
 [[5 4]
 [3 4]]
another product
 [[5 4]
 [3 4]]
